runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /set-webhook
  login: admin
  script: main.app
- url: /.*
  script: main.app
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

libraries:
- name: webapp2
  version: "2.5.2"
